[package]
name = "src-in-memory-infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"

[dependencies.src-domain]
path = "../src-domain"

[dev-dependencies]
tokio = { version = "1.38.0", features = ["full"] }
