[package]
name = "src-in-memory-infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
src-domain = { version = "0.1.0", path = "../src-domain" }

[dev-dependencies]
anyhow = "1.0.86"
tokio = { version = "1.38.0", features = ["full"] }
